version: '2'

services:
  bind:
    restart: always
    image: hansbogert/bind-webmin:9.10.3
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    - "10000:10000/tcp"
    volumes:
    - /srv/docker/bind:/data
